* Doppel engine & game 
** Engine
*** World
    The world is built in a 3d voxel, minecraft-like way, only more
    crappy, I don't use a 3d engine but instead just have 6 sides of
    the cube I want to look at the world.

    The file format is not yet clear, I am thinking just a plain text
    file format.  The world will not be just blocks, because that's too
    minceraft, instead I'll make specific wall 3d tiles (think ASCII
    box drawing but then 3d)
    
    Instead of just rendering each block I have to figure out some
    culling, (?front to back bounding-box exclusion?) I have ideas about
    some dynamic render-textures that could be helpful
    
**** TODO 
     - [X] Figure out culling front to back
     - [ ] Make sprites for  sides looking at various wall formation blocks
 
*** Entities
    There will be a few hundred 'smart' entities and many more dumb
    ones, the smart ones are 'actors' that have collision, AI,
    path-finding, animation and then some more. The dumber ones are
    just static objects in the world, perhaps some of them will have
    some animateable behaviors.
*** Debug
** Game





